# NumPy Indexing and Selection
In this lecture we will discuss how to select elements or groups of elements from an array.

In [3]:
import numpy as np

In [4]:
arr=np.arange(0,13)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
arr[0:3]

array([0, 1, 2])

In [9]:
arr[8:]

array([ 8,  9, 10, 11, 12])

In [10]:
array_sliding=arr[0:6]

In [11]:
array_sliding[:]=99

In [12]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12])

In [13]:
array_sliding=arr.copy()

In [14]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12])

In [15]:
array_sliding[:]=100
array_sliding

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12])

# Indexing a 2D array (matrices)
The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend usually using the comma notation for clarity.

In [17]:
array_two_d_array=np.array([[1,2,3],[2,3,4],[5,6,7]])

In [18]:
array_two_d_array

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [19]:
array_two_d_array[1,2]

4