# NumPy Arrays


In [1]:
import numpy as np

In [9]:
array=np.array([1,3,5])

In [10]:
array

array([1, 3, 5])

In [11]:
mult_array=np.array([[1,3,4],[2,3,4],[2,4,6]])

In [12]:
mult_array

array([[1, 3, 4],
       [2, 3, 4],
       [2, 4, 6]])

# Built-in Method

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.arange(0.1,3)

array([0.1, 1.1, 2.1])

#zeros and ones

In [21]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
arr=np.ones((2,2))

In [26]:
arr

array([[1., 1.],
       [1., 1.]])

In [28]:
arr[0]

array([1., 1.])

# linspace
Return evenly spaced numbers over a specified interval.

In [31]:
np.linspace(0,7,4)

array([0.        , 2.33333333, 4.66666667, 7.        ])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.random.rand(2)

array([0.95765298, 0.47640717])

In [39]:
np.random.randn(5)

array([ 0.95240493, -0.33357596,  0.72107609, -0.41372798,  0.11658289])

In [41]:
np.random.randint(3,5)

4

In [3]:
arr=np.arange(25)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr.max()

24

In [48]:
arr.argmin()

0

In [49]:
arr.mean()

12.0

In [51]:
arr.shape

(25,)

# # great job

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
d_aray=arr.reshape(5,5)

In [14]:
d_aray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
d_aray[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
arr>6

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [21]:
bool_arr=arr>6

In [22]:
bool_arr

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [23]:
arr[bool_arr]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24])